version: '3.9'

services:
  api: &api
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: local-compressor
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    restart: unless-stopped
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=rabbituser
      - RABBITMQ_DEFAULT_PASS=rabbitpass
    ports:
      - 5672:5672
      - 15672:15672

  celery:
    <<: *api
    # Remove watchfiles in production: watchfiles auto reloads celery when code changes
    command: watchfiles --filter python 'celery -A core worker --loglevel=info'
    ports: []
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - api 
      - rabbitmq

  celery-beat:
    <<: *api
    command: celery -A core beat -l info
    ports: []
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    depends_on:
      - celery
      - rabbitmq

  dashboard:
    <<: *api
    command: celery --broker=${RABBITMQ_URL} flower --port=5555
    ports:
      - '25556:5555'
    env_file:
      - ./.env
    depends_on:
      - api
      - celery
      - rabbitmq

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=compressor_db_user
      - POSTGRES_PASSWORD=compressor_password
      - POSTGRES_DB=compressor_db